### ISSUE TITLE
Add Time Schedule

### ISSUE THREAD

**Issue by JubairRahman** [abdellatif-laghjaj/todo-list#1]
It will be great if you incorporate Time schedule for every task

**Comment by abdellatif-laghjaj** [comment]
Can you explain more what did u mean ?

**Comment by JubairRahman** [comment]
I am adding something on ToDo List and I also want to show the time when I write 
Example: 
1. Morning Exercise >> Time: 6.00AM to 7.00 AM.
2. Coffe Break >> Time: 4.30PM to 5.00PM

**Comment by abdellatif-laghjaj** [comment]
Oh got you, so u mean to add a time related to each task?

**Comment by JubairRahman** [comment]
Yes sir

**Comment by abdellatif-laghjaj** [comment]
Oh nice
okay, when I found free time, I will implement it
Thanks for the idea

**Comment by JubairRahman** [comment]
Thank you sir.
You can check out my repo. And starred them to help me as well. ❤️❤️❤️

**Comment by abdellatif-laghjaj** [comment]
Hello,
check it now, i add some new updates

**Comment by JubairRahman** [comment]
Thank you
