### ISSUE TITLE
Todo Item exceeds container when large description

### ISSUE THREAD

**Issue by defiresearchers** [abdellatif-laghjaj/todo-list#2]
<img width="947" alt="Screenshot 2023-09-07 at 01 32 49" src="https://github.com/abdellatif-laghjaj/todo-list/assets/83651617/8898f2c0-f9ce-4076-8dbe-2fc975dc1fe9">

**Comment by abdellatif-laghjaj** [comment]
Thanks for the feedback @defiresearchers,
when i have a free time i will fix it

**Comment by abdellatif-laghjaj** [comment]
Hello thanks for waiting
I fixed the issue
