### ISSUE TITLE
pending issue

### ISSUE THREAD

**Issue by Rajvardhan1003** [abdellatif-laghjaj/todo-list#3]
when the task is completed and we select tick mark it is not showing completed can u help me fix it asap? 
![Screenshot 2023-10-14 221325](https://github.com/abdellatif-laghjaj/todo-list/assets/139889391/9d1da1e8-1733-43e7-a94a-5da5a7ac615e)
![Screenshot 2023-10-14 221311](https://github.com/abdellatif-laghjaj/todo-list/assets/139889391/fee98c6f-7830-4f36-857b-fa0b3bef52ba)

**Comment by abdellatif-laghjaj** [comment]
Hello thanks for the issue
I fixed it, u can checked it now GG
